/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface AppAutocompleteApi {}
  interface AppAutocompleteDemo {}
  interface AppAutocompleteTabs {}
  interface AppButtonDemo {}
  interface AppButtonTabs {}
  interface AppCardActionDemo {}
  interface AppCardActionTabs {}
  interface AppCardContentDemo {}
  interface AppCardContentTabs {}
  interface AppCardDemo {}
  interface AppCardTabs {}
  interface AppCheckboxDemo {}
  interface AppCheckboxTabs {}
  interface AppChipsDemo {}
  interface AppChipsTabs {}
  interface AppDatatableDemo {}
  interface AppDatatableTabs {}
  interface AppDateFieldDemo {}
  interface AppDateFieldTabs {}
  interface AppDatepickerDemo {}
  interface AppDatepickerTabs {}
  interface AppDemoCodeBlock {
    'blockTitle': string;
  }
  interface AppDemoTemplatePage {}
  interface AppDialogDemo {}
  interface AppDialogTabs {}
  interface AppDrawerDemo {}
  interface AppDrawerListItemDemo {}
  interface AppDrawerListItemTabs {}
  interface AppDrawerTabs {}
  interface AppDrawerWithTopAppBarDemo {}
  interface AppDrawerWithTopAppBarTabs {}
  interface AppDropdownDemo {}
  interface AppDropdownTabs {}
  interface AppExpansionPanelDemo {}
  interface AppExpansionPanelTabs {}
  interface AppFabDemo {}
  interface AppFabTabs {}
  interface AppFormFieldDemo {}
  interface AppFormFieldTabs {}
  interface AppHeadlineDemo {}
  interface AppHeadlineTabs {}
  interface AppHome {}
  interface AppIconButtonDemo {}
  interface AppIconButtonTabs {}
  interface AppIconDemo {}
  interface AppIconTabs {}
  interface AppIntroductionPage {}
  interface AppLinearProgressDemo {}
  interface AppLinearProgressTabs {}
  interface AppListDemo {}
  interface AppListItemCheckboxDemo {}
  interface AppListItemCheckboxTabs {}
  interface AppListItemDemo {}
  interface AppListItemTabs {}
  interface AppListTabs {}
  interface AppMenuDemo {}
  interface AppMenuTabs {}
  interface AppMultipleSelectDemo {}
  interface AppMultipleSelectTabs {}
  interface AppRadioDemo {}
  interface AppRadioGroupDemo {}
  interface AppRadioGroupTabs {}
  interface AppRadioTabs {}
  interface AppRoot {}
  interface AppSelectApi {}
  interface AppSelectDemo {}
  interface AppSelectTabs {}
  interface AppSnackbarDemo {}
  interface AppSnackbarTabs {}
  interface AppStepperDemo {}
  interface AppStepperTabs {}
  interface AppSubtitleDemo {}
  interface AppSubtitleTabs {}
  interface AppSwitchDemo {}
  interface AppSwitchTabs {}
  interface AppTabsDemo {}
  interface AppTabsTabs {}
  interface AppTextAreaDemo {}
  interface AppTextAreaTabs {}
  interface AppTextFieldDemo {}
  interface AppTextFieldTabs {}
  interface AppTimeFieldDemo {}
  interface AppTimeFieldTabs {}
  interface AppTimepickerDemo {}
  interface AppTimepickerTabs {}
  interface AppTopAppBarActionDemo {}
  interface AppTopAppBarActionTabs {}
  interface AppTopAppBarDemo {}
  interface AppTopAppBarTabs {}
}

declare global {


  interface HTMLAppAutocompleteApiElement extends Components.AppAutocompleteApi, HTMLStencilElement {}
  var HTMLAppAutocompleteApiElement: {
    prototype: HTMLAppAutocompleteApiElement;
    new (): HTMLAppAutocompleteApiElement;
  };

  interface HTMLAppAutocompleteDemoElement extends Components.AppAutocompleteDemo, HTMLStencilElement {}
  var HTMLAppAutocompleteDemoElement: {
    prototype: HTMLAppAutocompleteDemoElement;
    new (): HTMLAppAutocompleteDemoElement;
  };

  interface HTMLAppAutocompleteTabsElement extends Components.AppAutocompleteTabs, HTMLStencilElement {}
  var HTMLAppAutocompleteTabsElement: {
    prototype: HTMLAppAutocompleteTabsElement;
    new (): HTMLAppAutocompleteTabsElement;
  };

  interface HTMLAppButtonDemoElement extends Components.AppButtonDemo, HTMLStencilElement {}
  var HTMLAppButtonDemoElement: {
    prototype: HTMLAppButtonDemoElement;
    new (): HTMLAppButtonDemoElement;
  };

  interface HTMLAppButtonTabsElement extends Components.AppButtonTabs, HTMLStencilElement {}
  var HTMLAppButtonTabsElement: {
    prototype: HTMLAppButtonTabsElement;
    new (): HTMLAppButtonTabsElement;
  };

  interface HTMLAppCardActionDemoElement extends Components.AppCardActionDemo, HTMLStencilElement {}
  var HTMLAppCardActionDemoElement: {
    prototype: HTMLAppCardActionDemoElement;
    new (): HTMLAppCardActionDemoElement;
  };

  interface HTMLAppCardActionTabsElement extends Components.AppCardActionTabs, HTMLStencilElement {}
  var HTMLAppCardActionTabsElement: {
    prototype: HTMLAppCardActionTabsElement;
    new (): HTMLAppCardActionTabsElement;
  };

  interface HTMLAppCardContentDemoElement extends Components.AppCardContentDemo, HTMLStencilElement {}
  var HTMLAppCardContentDemoElement: {
    prototype: HTMLAppCardContentDemoElement;
    new (): HTMLAppCardContentDemoElement;
  };

  interface HTMLAppCardContentTabsElement extends Components.AppCardContentTabs, HTMLStencilElement {}
  var HTMLAppCardContentTabsElement: {
    prototype: HTMLAppCardContentTabsElement;
    new (): HTMLAppCardContentTabsElement;
  };

  interface HTMLAppCardDemoElement extends Components.AppCardDemo, HTMLStencilElement {}
  var HTMLAppCardDemoElement: {
    prototype: HTMLAppCardDemoElement;
    new (): HTMLAppCardDemoElement;
  };

  interface HTMLAppCardTabsElement extends Components.AppCardTabs, HTMLStencilElement {}
  var HTMLAppCardTabsElement: {
    prototype: HTMLAppCardTabsElement;
    new (): HTMLAppCardTabsElement;
  };

  interface HTMLAppCheckboxDemoElement extends Components.AppCheckboxDemo, HTMLStencilElement {}
  var HTMLAppCheckboxDemoElement: {
    prototype: HTMLAppCheckboxDemoElement;
    new (): HTMLAppCheckboxDemoElement;
  };

  interface HTMLAppCheckboxTabsElement extends Components.AppCheckboxTabs, HTMLStencilElement {}
  var HTMLAppCheckboxTabsElement: {
    prototype: HTMLAppCheckboxTabsElement;
    new (): HTMLAppCheckboxTabsElement;
  };

  interface HTMLAppChipsDemoElement extends Components.AppChipsDemo, HTMLStencilElement {}
  var HTMLAppChipsDemoElement: {
    prototype: HTMLAppChipsDemoElement;
    new (): HTMLAppChipsDemoElement;
  };

  interface HTMLAppChipsTabsElement extends Components.AppChipsTabs, HTMLStencilElement {}
  var HTMLAppChipsTabsElement: {
    prototype: HTMLAppChipsTabsElement;
    new (): HTMLAppChipsTabsElement;
  };

  interface HTMLAppDatatableDemoElement extends Components.AppDatatableDemo, HTMLStencilElement {}
  var HTMLAppDatatableDemoElement: {
    prototype: HTMLAppDatatableDemoElement;
    new (): HTMLAppDatatableDemoElement;
  };

  interface HTMLAppDatatableTabsElement extends Components.AppDatatableTabs, HTMLStencilElement {}
  var HTMLAppDatatableTabsElement: {
    prototype: HTMLAppDatatableTabsElement;
    new (): HTMLAppDatatableTabsElement;
  };

  interface HTMLAppDateFieldDemoElement extends Components.AppDateFieldDemo, HTMLStencilElement {}
  var HTMLAppDateFieldDemoElement: {
    prototype: HTMLAppDateFieldDemoElement;
    new (): HTMLAppDateFieldDemoElement;
  };

  interface HTMLAppDateFieldTabsElement extends Components.AppDateFieldTabs, HTMLStencilElement {}
  var HTMLAppDateFieldTabsElement: {
    prototype: HTMLAppDateFieldTabsElement;
    new (): HTMLAppDateFieldTabsElement;
  };

  interface HTMLAppDatepickerDemoElement extends Components.AppDatepickerDemo, HTMLStencilElement {}
  var HTMLAppDatepickerDemoElement: {
    prototype: HTMLAppDatepickerDemoElement;
    new (): HTMLAppDatepickerDemoElement;
  };

  interface HTMLAppDatepickerTabsElement extends Components.AppDatepickerTabs, HTMLStencilElement {}
  var HTMLAppDatepickerTabsElement: {
    prototype: HTMLAppDatepickerTabsElement;
    new (): HTMLAppDatepickerTabsElement;
  };

  interface HTMLAppDemoCodeBlockElement extends Components.AppDemoCodeBlock, HTMLStencilElement {}
  var HTMLAppDemoCodeBlockElement: {
    prototype: HTMLAppDemoCodeBlockElement;
    new (): HTMLAppDemoCodeBlockElement;
  };

  interface HTMLAppDemoTemplatePageElement extends Components.AppDemoTemplatePage, HTMLStencilElement {}
  var HTMLAppDemoTemplatePageElement: {
    prototype: HTMLAppDemoTemplatePageElement;
    new (): HTMLAppDemoTemplatePageElement;
  };

  interface HTMLAppDialogDemoElement extends Components.AppDialogDemo, HTMLStencilElement {}
  var HTMLAppDialogDemoElement: {
    prototype: HTMLAppDialogDemoElement;
    new (): HTMLAppDialogDemoElement;
  };

  interface HTMLAppDialogTabsElement extends Components.AppDialogTabs, HTMLStencilElement {}
  var HTMLAppDialogTabsElement: {
    prototype: HTMLAppDialogTabsElement;
    new (): HTMLAppDialogTabsElement;
  };

  interface HTMLAppDrawerDemoElement extends Components.AppDrawerDemo, HTMLStencilElement {}
  var HTMLAppDrawerDemoElement: {
    prototype: HTMLAppDrawerDemoElement;
    new (): HTMLAppDrawerDemoElement;
  };

  interface HTMLAppDrawerListItemDemoElement extends Components.AppDrawerListItemDemo, HTMLStencilElement {}
  var HTMLAppDrawerListItemDemoElement: {
    prototype: HTMLAppDrawerListItemDemoElement;
    new (): HTMLAppDrawerListItemDemoElement;
  };

  interface HTMLAppDrawerListItemTabsElement extends Components.AppDrawerListItemTabs, HTMLStencilElement {}
  var HTMLAppDrawerListItemTabsElement: {
    prototype: HTMLAppDrawerListItemTabsElement;
    new (): HTMLAppDrawerListItemTabsElement;
  };

  interface HTMLAppDrawerTabsElement extends Components.AppDrawerTabs, HTMLStencilElement {}
  var HTMLAppDrawerTabsElement: {
    prototype: HTMLAppDrawerTabsElement;
    new (): HTMLAppDrawerTabsElement;
  };

  interface HTMLAppDrawerWithTopAppBarDemoElement extends Components.AppDrawerWithTopAppBarDemo, HTMLStencilElement {}
  var HTMLAppDrawerWithTopAppBarDemoElement: {
    prototype: HTMLAppDrawerWithTopAppBarDemoElement;
    new (): HTMLAppDrawerWithTopAppBarDemoElement;
  };

  interface HTMLAppDrawerWithTopAppBarTabsElement extends Components.AppDrawerWithTopAppBarTabs, HTMLStencilElement {}
  var HTMLAppDrawerWithTopAppBarTabsElement: {
    prototype: HTMLAppDrawerWithTopAppBarTabsElement;
    new (): HTMLAppDrawerWithTopAppBarTabsElement;
  };

  interface HTMLAppDropdownDemoElement extends Components.AppDropdownDemo, HTMLStencilElement {}
  var HTMLAppDropdownDemoElement: {
    prototype: HTMLAppDropdownDemoElement;
    new (): HTMLAppDropdownDemoElement;
  };

  interface HTMLAppDropdownTabsElement extends Components.AppDropdownTabs, HTMLStencilElement {}
  var HTMLAppDropdownTabsElement: {
    prototype: HTMLAppDropdownTabsElement;
    new (): HTMLAppDropdownTabsElement;
  };

  interface HTMLAppExpansionPanelDemoElement extends Components.AppExpansionPanelDemo, HTMLStencilElement {}
  var HTMLAppExpansionPanelDemoElement: {
    prototype: HTMLAppExpansionPanelDemoElement;
    new (): HTMLAppExpansionPanelDemoElement;
  };

  interface HTMLAppExpansionPanelTabsElement extends Components.AppExpansionPanelTabs, HTMLStencilElement {}
  var HTMLAppExpansionPanelTabsElement: {
    prototype: HTMLAppExpansionPanelTabsElement;
    new (): HTMLAppExpansionPanelTabsElement;
  };

  interface HTMLAppFabDemoElement extends Components.AppFabDemo, HTMLStencilElement {}
  var HTMLAppFabDemoElement: {
    prototype: HTMLAppFabDemoElement;
    new (): HTMLAppFabDemoElement;
  };

  interface HTMLAppFabTabsElement extends Components.AppFabTabs, HTMLStencilElement {}
  var HTMLAppFabTabsElement: {
    prototype: HTMLAppFabTabsElement;
    new (): HTMLAppFabTabsElement;
  };

  interface HTMLAppFormFieldDemoElement extends Components.AppFormFieldDemo, HTMLStencilElement {}
  var HTMLAppFormFieldDemoElement: {
    prototype: HTMLAppFormFieldDemoElement;
    new (): HTMLAppFormFieldDemoElement;
  };

  interface HTMLAppFormFieldTabsElement extends Components.AppFormFieldTabs, HTMLStencilElement {}
  var HTMLAppFormFieldTabsElement: {
    prototype: HTMLAppFormFieldTabsElement;
    new (): HTMLAppFormFieldTabsElement;
  };

  interface HTMLAppHeadlineDemoElement extends Components.AppHeadlineDemo, HTMLStencilElement {}
  var HTMLAppHeadlineDemoElement: {
    prototype: HTMLAppHeadlineDemoElement;
    new (): HTMLAppHeadlineDemoElement;
  };

  interface HTMLAppHeadlineTabsElement extends Components.AppHeadlineTabs, HTMLStencilElement {}
  var HTMLAppHeadlineTabsElement: {
    prototype: HTMLAppHeadlineTabsElement;
    new (): HTMLAppHeadlineTabsElement;
  };

  interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {}
  var HTMLAppHomeElement: {
    prototype: HTMLAppHomeElement;
    new (): HTMLAppHomeElement;
  };

  interface HTMLAppIconButtonDemoElement extends Components.AppIconButtonDemo, HTMLStencilElement {}
  var HTMLAppIconButtonDemoElement: {
    prototype: HTMLAppIconButtonDemoElement;
    new (): HTMLAppIconButtonDemoElement;
  };

  interface HTMLAppIconButtonTabsElement extends Components.AppIconButtonTabs, HTMLStencilElement {}
  var HTMLAppIconButtonTabsElement: {
    prototype: HTMLAppIconButtonTabsElement;
    new (): HTMLAppIconButtonTabsElement;
  };

  interface HTMLAppIconDemoElement extends Components.AppIconDemo, HTMLStencilElement {}
  var HTMLAppIconDemoElement: {
    prototype: HTMLAppIconDemoElement;
    new (): HTMLAppIconDemoElement;
  };

  interface HTMLAppIconTabsElement extends Components.AppIconTabs, HTMLStencilElement {}
  var HTMLAppIconTabsElement: {
    prototype: HTMLAppIconTabsElement;
    new (): HTMLAppIconTabsElement;
  };

  interface HTMLAppIntroductionPageElement extends Components.AppIntroductionPage, HTMLStencilElement {}
  var HTMLAppIntroductionPageElement: {
    prototype: HTMLAppIntroductionPageElement;
    new (): HTMLAppIntroductionPageElement;
  };

  interface HTMLAppLinearProgressDemoElement extends Components.AppLinearProgressDemo, HTMLStencilElement {}
  var HTMLAppLinearProgressDemoElement: {
    prototype: HTMLAppLinearProgressDemoElement;
    new (): HTMLAppLinearProgressDemoElement;
  };

  interface HTMLAppLinearProgressTabsElement extends Components.AppLinearProgressTabs, HTMLStencilElement {}
  var HTMLAppLinearProgressTabsElement: {
    prototype: HTMLAppLinearProgressTabsElement;
    new (): HTMLAppLinearProgressTabsElement;
  };

  interface HTMLAppListDemoElement extends Components.AppListDemo, HTMLStencilElement {}
  var HTMLAppListDemoElement: {
    prototype: HTMLAppListDemoElement;
    new (): HTMLAppListDemoElement;
  };

  interface HTMLAppListItemCheckboxDemoElement extends Components.AppListItemCheckboxDemo, HTMLStencilElement {}
  var HTMLAppListItemCheckboxDemoElement: {
    prototype: HTMLAppListItemCheckboxDemoElement;
    new (): HTMLAppListItemCheckboxDemoElement;
  };

  interface HTMLAppListItemCheckboxTabsElement extends Components.AppListItemCheckboxTabs, HTMLStencilElement {}
  var HTMLAppListItemCheckboxTabsElement: {
    prototype: HTMLAppListItemCheckboxTabsElement;
    new (): HTMLAppListItemCheckboxTabsElement;
  };

  interface HTMLAppListItemDemoElement extends Components.AppListItemDemo, HTMLStencilElement {}
  var HTMLAppListItemDemoElement: {
    prototype: HTMLAppListItemDemoElement;
    new (): HTMLAppListItemDemoElement;
  };

  interface HTMLAppListItemTabsElement extends Components.AppListItemTabs, HTMLStencilElement {}
  var HTMLAppListItemTabsElement: {
    prototype: HTMLAppListItemTabsElement;
    new (): HTMLAppListItemTabsElement;
  };

  interface HTMLAppListTabsElement extends Components.AppListTabs, HTMLStencilElement {}
  var HTMLAppListTabsElement: {
    prototype: HTMLAppListTabsElement;
    new (): HTMLAppListTabsElement;
  };

  interface HTMLAppMenuDemoElement extends Components.AppMenuDemo, HTMLStencilElement {}
  var HTMLAppMenuDemoElement: {
    prototype: HTMLAppMenuDemoElement;
    new (): HTMLAppMenuDemoElement;
  };

  interface HTMLAppMenuTabsElement extends Components.AppMenuTabs, HTMLStencilElement {}
  var HTMLAppMenuTabsElement: {
    prototype: HTMLAppMenuTabsElement;
    new (): HTMLAppMenuTabsElement;
  };

  interface HTMLAppMultipleSelectDemoElement extends Components.AppMultipleSelectDemo, HTMLStencilElement {}
  var HTMLAppMultipleSelectDemoElement: {
    prototype: HTMLAppMultipleSelectDemoElement;
    new (): HTMLAppMultipleSelectDemoElement;
  };

  interface HTMLAppMultipleSelectTabsElement extends Components.AppMultipleSelectTabs, HTMLStencilElement {}
  var HTMLAppMultipleSelectTabsElement: {
    prototype: HTMLAppMultipleSelectTabsElement;
    new (): HTMLAppMultipleSelectTabsElement;
  };

  interface HTMLAppRadioDemoElement extends Components.AppRadioDemo, HTMLStencilElement {}
  var HTMLAppRadioDemoElement: {
    prototype: HTMLAppRadioDemoElement;
    new (): HTMLAppRadioDemoElement;
  };

  interface HTMLAppRadioGroupDemoElement extends Components.AppRadioGroupDemo, HTMLStencilElement {}
  var HTMLAppRadioGroupDemoElement: {
    prototype: HTMLAppRadioGroupDemoElement;
    new (): HTMLAppRadioGroupDemoElement;
  };

  interface HTMLAppRadioGroupTabsElement extends Components.AppRadioGroupTabs, HTMLStencilElement {}
  var HTMLAppRadioGroupTabsElement: {
    prototype: HTMLAppRadioGroupTabsElement;
    new (): HTMLAppRadioGroupTabsElement;
  };

  interface HTMLAppRadioTabsElement extends Components.AppRadioTabs, HTMLStencilElement {}
  var HTMLAppRadioTabsElement: {
    prototype: HTMLAppRadioTabsElement;
    new (): HTMLAppRadioTabsElement;
  };

  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLAppSelectApiElement extends Components.AppSelectApi, HTMLStencilElement {}
  var HTMLAppSelectApiElement: {
    prototype: HTMLAppSelectApiElement;
    new (): HTMLAppSelectApiElement;
  };

  interface HTMLAppSelectDemoElement extends Components.AppSelectDemo, HTMLStencilElement {}
  var HTMLAppSelectDemoElement: {
    prototype: HTMLAppSelectDemoElement;
    new (): HTMLAppSelectDemoElement;
  };

  interface HTMLAppSelectTabsElement extends Components.AppSelectTabs, HTMLStencilElement {}
  var HTMLAppSelectTabsElement: {
    prototype: HTMLAppSelectTabsElement;
    new (): HTMLAppSelectTabsElement;
  };

  interface HTMLAppSnackbarDemoElement extends Components.AppSnackbarDemo, HTMLStencilElement {}
  var HTMLAppSnackbarDemoElement: {
    prototype: HTMLAppSnackbarDemoElement;
    new (): HTMLAppSnackbarDemoElement;
  };

  interface HTMLAppSnackbarTabsElement extends Components.AppSnackbarTabs, HTMLStencilElement {}
  var HTMLAppSnackbarTabsElement: {
    prototype: HTMLAppSnackbarTabsElement;
    new (): HTMLAppSnackbarTabsElement;
  };

  interface HTMLAppStepperDemoElement extends Components.AppStepperDemo, HTMLStencilElement {}
  var HTMLAppStepperDemoElement: {
    prototype: HTMLAppStepperDemoElement;
    new (): HTMLAppStepperDemoElement;
  };

  interface HTMLAppStepperTabsElement extends Components.AppStepperTabs, HTMLStencilElement {}
  var HTMLAppStepperTabsElement: {
    prototype: HTMLAppStepperTabsElement;
    new (): HTMLAppStepperTabsElement;
  };

  interface HTMLAppSubtitleDemoElement extends Components.AppSubtitleDemo, HTMLStencilElement {}
  var HTMLAppSubtitleDemoElement: {
    prototype: HTMLAppSubtitleDemoElement;
    new (): HTMLAppSubtitleDemoElement;
  };

  interface HTMLAppSubtitleTabsElement extends Components.AppSubtitleTabs, HTMLStencilElement {}
  var HTMLAppSubtitleTabsElement: {
    prototype: HTMLAppSubtitleTabsElement;
    new (): HTMLAppSubtitleTabsElement;
  };

  interface HTMLAppSwitchDemoElement extends Components.AppSwitchDemo, HTMLStencilElement {}
  var HTMLAppSwitchDemoElement: {
    prototype: HTMLAppSwitchDemoElement;
    new (): HTMLAppSwitchDemoElement;
  };

  interface HTMLAppSwitchTabsElement extends Components.AppSwitchTabs, HTMLStencilElement {}
  var HTMLAppSwitchTabsElement: {
    prototype: HTMLAppSwitchTabsElement;
    new (): HTMLAppSwitchTabsElement;
  };

  interface HTMLAppTabsDemoElement extends Components.AppTabsDemo, HTMLStencilElement {}
  var HTMLAppTabsDemoElement: {
    prototype: HTMLAppTabsDemoElement;
    new (): HTMLAppTabsDemoElement;
  };

  interface HTMLAppTabsTabsElement extends Components.AppTabsTabs, HTMLStencilElement {}
  var HTMLAppTabsTabsElement: {
    prototype: HTMLAppTabsTabsElement;
    new (): HTMLAppTabsTabsElement;
  };

  interface HTMLAppTextAreaDemoElement extends Components.AppTextAreaDemo, HTMLStencilElement {}
  var HTMLAppTextAreaDemoElement: {
    prototype: HTMLAppTextAreaDemoElement;
    new (): HTMLAppTextAreaDemoElement;
  };

  interface HTMLAppTextAreaTabsElement extends Components.AppTextAreaTabs, HTMLStencilElement {}
  var HTMLAppTextAreaTabsElement: {
    prototype: HTMLAppTextAreaTabsElement;
    new (): HTMLAppTextAreaTabsElement;
  };

  interface HTMLAppTextFieldDemoElement extends Components.AppTextFieldDemo, HTMLStencilElement {}
  var HTMLAppTextFieldDemoElement: {
    prototype: HTMLAppTextFieldDemoElement;
    new (): HTMLAppTextFieldDemoElement;
  };

  interface HTMLAppTextFieldTabsElement extends Components.AppTextFieldTabs, HTMLStencilElement {}
  var HTMLAppTextFieldTabsElement: {
    prototype: HTMLAppTextFieldTabsElement;
    new (): HTMLAppTextFieldTabsElement;
  };

  interface HTMLAppTimeFieldDemoElement extends Components.AppTimeFieldDemo, HTMLStencilElement {}
  var HTMLAppTimeFieldDemoElement: {
    prototype: HTMLAppTimeFieldDemoElement;
    new (): HTMLAppTimeFieldDemoElement;
  };

  interface HTMLAppTimeFieldTabsElement extends Components.AppTimeFieldTabs, HTMLStencilElement {}
  var HTMLAppTimeFieldTabsElement: {
    prototype: HTMLAppTimeFieldTabsElement;
    new (): HTMLAppTimeFieldTabsElement;
  };

  interface HTMLAppTimepickerDemoElement extends Components.AppTimepickerDemo, HTMLStencilElement {}
  var HTMLAppTimepickerDemoElement: {
    prototype: HTMLAppTimepickerDemoElement;
    new (): HTMLAppTimepickerDemoElement;
  };

  interface HTMLAppTimepickerTabsElement extends Components.AppTimepickerTabs, HTMLStencilElement {}
  var HTMLAppTimepickerTabsElement: {
    prototype: HTMLAppTimepickerTabsElement;
    new (): HTMLAppTimepickerTabsElement;
  };

  interface HTMLAppTopAppBarActionDemoElement extends Components.AppTopAppBarActionDemo, HTMLStencilElement {}
  var HTMLAppTopAppBarActionDemoElement: {
    prototype: HTMLAppTopAppBarActionDemoElement;
    new (): HTMLAppTopAppBarActionDemoElement;
  };

  interface HTMLAppTopAppBarActionTabsElement extends Components.AppTopAppBarActionTabs, HTMLStencilElement {}
  var HTMLAppTopAppBarActionTabsElement: {
    prototype: HTMLAppTopAppBarActionTabsElement;
    new (): HTMLAppTopAppBarActionTabsElement;
  };

  interface HTMLAppTopAppBarDemoElement extends Components.AppTopAppBarDemo, HTMLStencilElement {}
  var HTMLAppTopAppBarDemoElement: {
    prototype: HTMLAppTopAppBarDemoElement;
    new (): HTMLAppTopAppBarDemoElement;
  };

  interface HTMLAppTopAppBarTabsElement extends Components.AppTopAppBarTabs, HTMLStencilElement {}
  var HTMLAppTopAppBarTabsElement: {
    prototype: HTMLAppTopAppBarTabsElement;
    new (): HTMLAppTopAppBarTabsElement;
  };
  interface HTMLElementTagNameMap {
    'app-autocomplete-api': HTMLAppAutocompleteApiElement;
    'app-autocomplete-demo': HTMLAppAutocompleteDemoElement;
    'app-autocomplete-tabs': HTMLAppAutocompleteTabsElement;
    'app-button-demo': HTMLAppButtonDemoElement;
    'app-button-tabs': HTMLAppButtonTabsElement;
    'app-card-action-demo': HTMLAppCardActionDemoElement;
    'app-card-action-tabs': HTMLAppCardActionTabsElement;
    'app-card-content-demo': HTMLAppCardContentDemoElement;
    'app-card-content-tabs': HTMLAppCardContentTabsElement;
    'app-card-demo': HTMLAppCardDemoElement;
    'app-card-tabs': HTMLAppCardTabsElement;
    'app-checkbox-demo': HTMLAppCheckboxDemoElement;
    'app-checkbox-tabs': HTMLAppCheckboxTabsElement;
    'app-chips-demo': HTMLAppChipsDemoElement;
    'app-chips-tabs': HTMLAppChipsTabsElement;
    'app-datatable-demo': HTMLAppDatatableDemoElement;
    'app-datatable-tabs': HTMLAppDatatableTabsElement;
    'app-date-field-demo': HTMLAppDateFieldDemoElement;
    'app-date-field-tabs': HTMLAppDateFieldTabsElement;
    'app-datepicker-demo': HTMLAppDatepickerDemoElement;
    'app-datepicker-tabs': HTMLAppDatepickerTabsElement;
    'app-demo-code-block': HTMLAppDemoCodeBlockElement;
    'app-demo-template-page': HTMLAppDemoTemplatePageElement;
    'app-dialog-demo': HTMLAppDialogDemoElement;
    'app-dialog-tabs': HTMLAppDialogTabsElement;
    'app-drawer-demo': HTMLAppDrawerDemoElement;
    'app-drawer-list-item-demo': HTMLAppDrawerListItemDemoElement;
    'app-drawer-list-item-tabs': HTMLAppDrawerListItemTabsElement;
    'app-drawer-tabs': HTMLAppDrawerTabsElement;
    'app-drawer-with-top-app-bar-demo': HTMLAppDrawerWithTopAppBarDemoElement;
    'app-drawer-with-top-app-bar-tabs': HTMLAppDrawerWithTopAppBarTabsElement;
    'app-dropdown-demo': HTMLAppDropdownDemoElement;
    'app-dropdown-tabs': HTMLAppDropdownTabsElement;
    'app-expansion-panel-demo': HTMLAppExpansionPanelDemoElement;
    'app-expansion-panel-tabs': HTMLAppExpansionPanelTabsElement;
    'app-fab-demo': HTMLAppFabDemoElement;
    'app-fab-tabs': HTMLAppFabTabsElement;
    'app-form-field-demo': HTMLAppFormFieldDemoElement;
    'app-form-field-tabs': HTMLAppFormFieldTabsElement;
    'app-headline-demo': HTMLAppHeadlineDemoElement;
    'app-headline-tabs': HTMLAppHeadlineTabsElement;
    'app-home': HTMLAppHomeElement;
    'app-icon-button-demo': HTMLAppIconButtonDemoElement;
    'app-icon-button-tabs': HTMLAppIconButtonTabsElement;
    'app-icon-demo': HTMLAppIconDemoElement;
    'app-icon-tabs': HTMLAppIconTabsElement;
    'app-introduction-page': HTMLAppIntroductionPageElement;
    'app-linear-progress-demo': HTMLAppLinearProgressDemoElement;
    'app-linear-progress-tabs': HTMLAppLinearProgressTabsElement;
    'app-list-demo': HTMLAppListDemoElement;
    'app-list-item-checkbox-demo': HTMLAppListItemCheckboxDemoElement;
    'app-list-item-checkbox-tabs': HTMLAppListItemCheckboxTabsElement;
    'app-list-item-demo': HTMLAppListItemDemoElement;
    'app-list-item-tabs': HTMLAppListItemTabsElement;
    'app-list-tabs': HTMLAppListTabsElement;
    'app-menu-demo': HTMLAppMenuDemoElement;
    'app-menu-tabs': HTMLAppMenuTabsElement;
    'app-multiple-select-demo': HTMLAppMultipleSelectDemoElement;
    'app-multiple-select-tabs': HTMLAppMultipleSelectTabsElement;
    'app-radio-demo': HTMLAppRadioDemoElement;
    'app-radio-group-demo': HTMLAppRadioGroupDemoElement;
    'app-radio-group-tabs': HTMLAppRadioGroupTabsElement;
    'app-radio-tabs': HTMLAppRadioTabsElement;
    'app-root': HTMLAppRootElement;
    'app-select-api': HTMLAppSelectApiElement;
    'app-select-demo': HTMLAppSelectDemoElement;
    'app-select-tabs': HTMLAppSelectTabsElement;
    'app-snackbar-demo': HTMLAppSnackbarDemoElement;
    'app-snackbar-tabs': HTMLAppSnackbarTabsElement;
    'app-stepper-demo': HTMLAppStepperDemoElement;
    'app-stepper-tabs': HTMLAppStepperTabsElement;
    'app-subtitle-demo': HTMLAppSubtitleDemoElement;
    'app-subtitle-tabs': HTMLAppSubtitleTabsElement;
    'app-switch-demo': HTMLAppSwitchDemoElement;
    'app-switch-tabs': HTMLAppSwitchTabsElement;
    'app-tabs-demo': HTMLAppTabsDemoElement;
    'app-tabs-tabs': HTMLAppTabsTabsElement;
    'app-text-area-demo': HTMLAppTextAreaDemoElement;
    'app-text-area-tabs': HTMLAppTextAreaTabsElement;
    'app-text-field-demo': HTMLAppTextFieldDemoElement;
    'app-text-field-tabs': HTMLAppTextFieldTabsElement;
    'app-time-field-demo': HTMLAppTimeFieldDemoElement;
    'app-time-field-tabs': HTMLAppTimeFieldTabsElement;
    'app-timepicker-demo': HTMLAppTimepickerDemoElement;
    'app-timepicker-tabs': HTMLAppTimepickerTabsElement;
    'app-top-app-bar-action-demo': HTMLAppTopAppBarActionDemoElement;
    'app-top-app-bar-action-tabs': HTMLAppTopAppBarActionTabsElement;
    'app-top-app-bar-demo': HTMLAppTopAppBarDemoElement;
    'app-top-app-bar-tabs': HTMLAppTopAppBarTabsElement;
  }
}

declare namespace LocalJSX {
  interface AppAutocompleteApi extends JSXBase.HTMLAttributes<HTMLAppAutocompleteApiElement> {}
  interface AppAutocompleteDemo extends JSXBase.HTMLAttributes<HTMLAppAutocompleteDemoElement> {}
  interface AppAutocompleteTabs extends JSXBase.HTMLAttributes<HTMLAppAutocompleteTabsElement> {}
  interface AppButtonDemo extends JSXBase.HTMLAttributes<HTMLAppButtonDemoElement> {}
  interface AppButtonTabs extends JSXBase.HTMLAttributes<HTMLAppButtonTabsElement> {}
  interface AppCardActionDemo extends JSXBase.HTMLAttributes<HTMLAppCardActionDemoElement> {}
  interface AppCardActionTabs extends JSXBase.HTMLAttributes<HTMLAppCardActionTabsElement> {}
  interface AppCardContentDemo extends JSXBase.HTMLAttributes<HTMLAppCardContentDemoElement> {}
  interface AppCardContentTabs extends JSXBase.HTMLAttributes<HTMLAppCardContentTabsElement> {}
  interface AppCardDemo extends JSXBase.HTMLAttributes<HTMLAppCardDemoElement> {}
  interface AppCardTabs extends JSXBase.HTMLAttributes<HTMLAppCardTabsElement> {}
  interface AppCheckboxDemo extends JSXBase.HTMLAttributes<HTMLAppCheckboxDemoElement> {}
  interface AppCheckboxTabs extends JSXBase.HTMLAttributes<HTMLAppCheckboxTabsElement> {}
  interface AppChipsDemo extends JSXBase.HTMLAttributes<HTMLAppChipsDemoElement> {}
  interface AppChipsTabs extends JSXBase.HTMLAttributes<HTMLAppChipsTabsElement> {}
  interface AppDatatableDemo extends JSXBase.HTMLAttributes<HTMLAppDatatableDemoElement> {}
  interface AppDatatableTabs extends JSXBase.HTMLAttributes<HTMLAppDatatableTabsElement> {}
  interface AppDateFieldDemo extends JSXBase.HTMLAttributes<HTMLAppDateFieldDemoElement> {}
  interface AppDateFieldTabs extends JSXBase.HTMLAttributes<HTMLAppDateFieldTabsElement> {}
  interface AppDatepickerDemo extends JSXBase.HTMLAttributes<HTMLAppDatepickerDemoElement> {}
  interface AppDatepickerTabs extends JSXBase.HTMLAttributes<HTMLAppDatepickerTabsElement> {}
  interface AppDemoCodeBlock extends JSXBase.HTMLAttributes<HTMLAppDemoCodeBlockElement> {
    'blockTitle'?: string;
  }
  interface AppDemoTemplatePage extends JSXBase.HTMLAttributes<HTMLAppDemoTemplatePageElement> {}
  interface AppDialogDemo extends JSXBase.HTMLAttributes<HTMLAppDialogDemoElement> {}
  interface AppDialogTabs extends JSXBase.HTMLAttributes<HTMLAppDialogTabsElement> {}
  interface AppDrawerDemo extends JSXBase.HTMLAttributes<HTMLAppDrawerDemoElement> {}
  interface AppDrawerListItemDemo extends JSXBase.HTMLAttributes<HTMLAppDrawerListItemDemoElement> {}
  interface AppDrawerListItemTabs extends JSXBase.HTMLAttributes<HTMLAppDrawerListItemTabsElement> {}
  interface AppDrawerTabs extends JSXBase.HTMLAttributes<HTMLAppDrawerTabsElement> {}
  interface AppDrawerWithTopAppBarDemo extends JSXBase.HTMLAttributes<HTMLAppDrawerWithTopAppBarDemoElement> {}
  interface AppDrawerWithTopAppBarTabs extends JSXBase.HTMLAttributes<HTMLAppDrawerWithTopAppBarTabsElement> {}
  interface AppDropdownDemo extends JSXBase.HTMLAttributes<HTMLAppDropdownDemoElement> {}
  interface AppDropdownTabs extends JSXBase.HTMLAttributes<HTMLAppDropdownTabsElement> {}
  interface AppExpansionPanelDemo extends JSXBase.HTMLAttributes<HTMLAppExpansionPanelDemoElement> {}
  interface AppExpansionPanelTabs extends JSXBase.HTMLAttributes<HTMLAppExpansionPanelTabsElement> {}
  interface AppFabDemo extends JSXBase.HTMLAttributes<HTMLAppFabDemoElement> {}
  interface AppFabTabs extends JSXBase.HTMLAttributes<HTMLAppFabTabsElement> {}
  interface AppFormFieldDemo extends JSXBase.HTMLAttributes<HTMLAppFormFieldDemoElement> {}
  interface AppFormFieldTabs extends JSXBase.HTMLAttributes<HTMLAppFormFieldTabsElement> {}
  interface AppHeadlineDemo extends JSXBase.HTMLAttributes<HTMLAppHeadlineDemoElement> {}
  interface AppHeadlineTabs extends JSXBase.HTMLAttributes<HTMLAppHeadlineTabsElement> {}
  interface AppHome extends JSXBase.HTMLAttributes<HTMLAppHomeElement> {}
  interface AppIconButtonDemo extends JSXBase.HTMLAttributes<HTMLAppIconButtonDemoElement> {}
  interface AppIconButtonTabs extends JSXBase.HTMLAttributes<HTMLAppIconButtonTabsElement> {}
  interface AppIconDemo extends JSXBase.HTMLAttributes<HTMLAppIconDemoElement> {}
  interface AppIconTabs extends JSXBase.HTMLAttributes<HTMLAppIconTabsElement> {}
  interface AppIntroductionPage extends JSXBase.HTMLAttributes<HTMLAppIntroductionPageElement> {}
  interface AppLinearProgressDemo extends JSXBase.HTMLAttributes<HTMLAppLinearProgressDemoElement> {}
  interface AppLinearProgressTabs extends JSXBase.HTMLAttributes<HTMLAppLinearProgressTabsElement> {}
  interface AppListDemo extends JSXBase.HTMLAttributes<HTMLAppListDemoElement> {}
  interface AppListItemCheckboxDemo extends JSXBase.HTMLAttributes<HTMLAppListItemCheckboxDemoElement> {}
  interface AppListItemCheckboxTabs extends JSXBase.HTMLAttributes<HTMLAppListItemCheckboxTabsElement> {}
  interface AppListItemDemo extends JSXBase.HTMLAttributes<HTMLAppListItemDemoElement> {}
  interface AppListItemTabs extends JSXBase.HTMLAttributes<HTMLAppListItemTabsElement> {}
  interface AppListTabs extends JSXBase.HTMLAttributes<HTMLAppListTabsElement> {}
  interface AppMenuDemo extends JSXBase.HTMLAttributes<HTMLAppMenuDemoElement> {}
  interface AppMenuTabs extends JSXBase.HTMLAttributes<HTMLAppMenuTabsElement> {}
  interface AppMultipleSelectDemo extends JSXBase.HTMLAttributes<HTMLAppMultipleSelectDemoElement> {}
  interface AppMultipleSelectTabs extends JSXBase.HTMLAttributes<HTMLAppMultipleSelectTabsElement> {}
  interface AppRadioDemo extends JSXBase.HTMLAttributes<HTMLAppRadioDemoElement> {}
  interface AppRadioGroupDemo extends JSXBase.HTMLAttributes<HTMLAppRadioGroupDemoElement> {}
  interface AppRadioGroupTabs extends JSXBase.HTMLAttributes<HTMLAppRadioGroupTabsElement> {}
  interface AppRadioTabs extends JSXBase.HTMLAttributes<HTMLAppRadioTabsElement> {}
  interface AppRoot extends JSXBase.HTMLAttributes<HTMLAppRootElement> {}
  interface AppSelectApi extends JSXBase.HTMLAttributes<HTMLAppSelectApiElement> {}
  interface AppSelectDemo extends JSXBase.HTMLAttributes<HTMLAppSelectDemoElement> {}
  interface AppSelectTabs extends JSXBase.HTMLAttributes<HTMLAppSelectTabsElement> {}
  interface AppSnackbarDemo extends JSXBase.HTMLAttributes<HTMLAppSnackbarDemoElement> {}
  interface AppSnackbarTabs extends JSXBase.HTMLAttributes<HTMLAppSnackbarTabsElement> {}
  interface AppStepperDemo extends JSXBase.HTMLAttributes<HTMLAppStepperDemoElement> {}
  interface AppStepperTabs extends JSXBase.HTMLAttributes<HTMLAppStepperTabsElement> {}
  interface AppSubtitleDemo extends JSXBase.HTMLAttributes<HTMLAppSubtitleDemoElement> {}
  interface AppSubtitleTabs extends JSXBase.HTMLAttributes<HTMLAppSubtitleTabsElement> {}
  interface AppSwitchDemo extends JSXBase.HTMLAttributes<HTMLAppSwitchDemoElement> {}
  interface AppSwitchTabs extends JSXBase.HTMLAttributes<HTMLAppSwitchTabsElement> {}
  interface AppTabsDemo extends JSXBase.HTMLAttributes<HTMLAppTabsDemoElement> {}
  interface AppTabsTabs extends JSXBase.HTMLAttributes<HTMLAppTabsTabsElement> {}
  interface AppTextAreaDemo extends JSXBase.HTMLAttributes<HTMLAppTextAreaDemoElement> {}
  interface AppTextAreaTabs extends JSXBase.HTMLAttributes<HTMLAppTextAreaTabsElement> {}
  interface AppTextFieldDemo extends JSXBase.HTMLAttributes<HTMLAppTextFieldDemoElement> {}
  interface AppTextFieldTabs extends JSXBase.HTMLAttributes<HTMLAppTextFieldTabsElement> {}
  interface AppTimeFieldDemo extends JSXBase.HTMLAttributes<HTMLAppTimeFieldDemoElement> {}
  interface AppTimeFieldTabs extends JSXBase.HTMLAttributes<HTMLAppTimeFieldTabsElement> {}
  interface AppTimepickerDemo extends JSXBase.HTMLAttributes<HTMLAppTimepickerDemoElement> {}
  interface AppTimepickerTabs extends JSXBase.HTMLAttributes<HTMLAppTimepickerTabsElement> {}
  interface AppTopAppBarActionDemo extends JSXBase.HTMLAttributes<HTMLAppTopAppBarActionDemoElement> {}
  interface AppTopAppBarActionTabs extends JSXBase.HTMLAttributes<HTMLAppTopAppBarActionTabsElement> {}
  interface AppTopAppBarDemo extends JSXBase.HTMLAttributes<HTMLAppTopAppBarDemoElement> {}
  interface AppTopAppBarTabs extends JSXBase.HTMLAttributes<HTMLAppTopAppBarTabsElement> {}

  interface IntrinsicElements {
    'app-autocomplete-api': AppAutocompleteApi;
    'app-autocomplete-demo': AppAutocompleteDemo;
    'app-autocomplete-tabs': AppAutocompleteTabs;
    'app-button-demo': AppButtonDemo;
    'app-button-tabs': AppButtonTabs;
    'app-card-action-demo': AppCardActionDemo;
    'app-card-action-tabs': AppCardActionTabs;
    'app-card-content-demo': AppCardContentDemo;
    'app-card-content-tabs': AppCardContentTabs;
    'app-card-demo': AppCardDemo;
    'app-card-tabs': AppCardTabs;
    'app-checkbox-demo': AppCheckboxDemo;
    'app-checkbox-tabs': AppCheckboxTabs;
    'app-chips-demo': AppChipsDemo;
    'app-chips-tabs': AppChipsTabs;
    'app-datatable-demo': AppDatatableDemo;
    'app-datatable-tabs': AppDatatableTabs;
    'app-date-field-demo': AppDateFieldDemo;
    'app-date-field-tabs': AppDateFieldTabs;
    'app-datepicker-demo': AppDatepickerDemo;
    'app-datepicker-tabs': AppDatepickerTabs;
    'app-demo-code-block': AppDemoCodeBlock;
    'app-demo-template-page': AppDemoTemplatePage;
    'app-dialog-demo': AppDialogDemo;
    'app-dialog-tabs': AppDialogTabs;
    'app-drawer-demo': AppDrawerDemo;
    'app-drawer-list-item-demo': AppDrawerListItemDemo;
    'app-drawer-list-item-tabs': AppDrawerListItemTabs;
    'app-drawer-tabs': AppDrawerTabs;
    'app-drawer-with-top-app-bar-demo': AppDrawerWithTopAppBarDemo;
    'app-drawer-with-top-app-bar-tabs': AppDrawerWithTopAppBarTabs;
    'app-dropdown-demo': AppDropdownDemo;
    'app-dropdown-tabs': AppDropdownTabs;
    'app-expansion-panel-demo': AppExpansionPanelDemo;
    'app-expansion-panel-tabs': AppExpansionPanelTabs;
    'app-fab-demo': AppFabDemo;
    'app-fab-tabs': AppFabTabs;
    'app-form-field-demo': AppFormFieldDemo;
    'app-form-field-tabs': AppFormFieldTabs;
    'app-headline-demo': AppHeadlineDemo;
    'app-headline-tabs': AppHeadlineTabs;
    'app-home': AppHome;
    'app-icon-button-demo': AppIconButtonDemo;
    'app-icon-button-tabs': AppIconButtonTabs;
    'app-icon-demo': AppIconDemo;
    'app-icon-tabs': AppIconTabs;
    'app-introduction-page': AppIntroductionPage;
    'app-linear-progress-demo': AppLinearProgressDemo;
    'app-linear-progress-tabs': AppLinearProgressTabs;
    'app-list-demo': AppListDemo;
    'app-list-item-checkbox-demo': AppListItemCheckboxDemo;
    'app-list-item-checkbox-tabs': AppListItemCheckboxTabs;
    'app-list-item-demo': AppListItemDemo;
    'app-list-item-tabs': AppListItemTabs;
    'app-list-tabs': AppListTabs;
    'app-menu-demo': AppMenuDemo;
    'app-menu-tabs': AppMenuTabs;
    'app-multiple-select-demo': AppMultipleSelectDemo;
    'app-multiple-select-tabs': AppMultipleSelectTabs;
    'app-radio-demo': AppRadioDemo;
    'app-radio-group-demo': AppRadioGroupDemo;
    'app-radio-group-tabs': AppRadioGroupTabs;
    'app-radio-tabs': AppRadioTabs;
    'app-root': AppRoot;
    'app-select-api': AppSelectApi;
    'app-select-demo': AppSelectDemo;
    'app-select-tabs': AppSelectTabs;
    'app-snackbar-demo': AppSnackbarDemo;
    'app-snackbar-tabs': AppSnackbarTabs;
    'app-stepper-demo': AppStepperDemo;
    'app-stepper-tabs': AppStepperTabs;
    'app-subtitle-demo': AppSubtitleDemo;
    'app-subtitle-tabs': AppSubtitleTabs;
    'app-switch-demo': AppSwitchDemo;
    'app-switch-tabs': AppSwitchTabs;
    'app-tabs-demo': AppTabsDemo;
    'app-tabs-tabs': AppTabsTabs;
    'app-text-area-demo': AppTextAreaDemo;
    'app-text-area-tabs': AppTextAreaTabs;
    'app-text-field-demo': AppTextFieldDemo;
    'app-text-field-tabs': AppTextFieldTabs;
    'app-time-field-demo': AppTimeFieldDemo;
    'app-time-field-tabs': AppTimeFieldTabs;
    'app-timepicker-demo': AppTimepickerDemo;
    'app-timepicker-tabs': AppTimepickerTabs;
    'app-top-app-bar-action-demo': AppTopAppBarActionDemo;
    'app-top-app-bar-action-tabs': AppTopAppBarActionTabs;
    'app-top-app-bar-demo': AppTopAppBarDemo;
    'app-top-app-bar-tabs': AppTopAppBarTabs;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


