language: node_js
node_js:
  - "10"
install:
  - npm install -g lerna
  - lerna bootstrap
script:
  - lerna run build
after_success:
  - git checkout $TRAVIS_BRANCH

deploy:
  - provider: script
    script: npx lerna publish from-git --yes
    skip_cleanup: true
    keep_history: true
    on:
      tags: true
