
import { Component, h, Host } from '@stencil/core';


@Component({
  tag: 'app-autocomplete-api',
  shadow: false
})
export class AutocompleteApi {

  /*
  * DO NOT EDIT THIS FILE !!!
  * It has been auto generated from :
  * https://github.com/GMV-centravet/materials/blob/master/src/components/autocomplete/readme.md
  */

  render() {
    return (
      <Host class={{'api-page':true}}>
      <h1>materials-autocomplete</h1>

<h2>Properties</h2>
<table>
<thead>
<tr>
<th>Property</th>
<th>Attribute</th>
<th>Description</th>
<th>Type</th>
<th>Default</th>
</tr>
</thead>
<tbody>
<tr>
<td><code>autocomplete</code></td>
<td>–</td>
<td>Function of autocompletion to pass to the element called during onInput of the text-field</td>
<td><code>(search: string) =&gt; Promise&lt;Map&lt;string, string&gt;&gt;</code></td>
<td><code>undefined</code></td>
</tr>
<tr>
<td><code>dense</code></td>
<td><code>dense</code></td>
<td>Apply low density on the element</td>
<td><code>boolean</code></td>
<td><code>false</code></td>
</tr>
<tr>
<td><code>label</code></td>
<td><code>label</code></td>
<td>Label of the autocomplete</td>
<td><code>string</code></td>
<td><code>undefined</code></td>
</tr>
<tr>
<td><code>value</code></td>
<td>–</td>
<td>Value of the autocomplete text-field composed by a label to be displayed in the text-field and a value that is a real value if no label given, label = value</td>
<td><code>&#123; label?: string; value: string; &#125;</code></td>
<td><code>undefined</code></td>
</tr>
</tbody>
</table>
<h2>Events</h2>
<table>
<thead>
<tr>
<th>Event</th>
<th>Description</th>
<th>Type</th>
</tr>
</thead>
<tbody>
<tr>
<td><code>change</code></td>
<td>Change event emitted when value is selected</td>
<td><code>CustomEvent&lt;any&gt;</code></td>
</tr>
</tbody>
</table>
<h2>Dependencies</h2>
<h3>Depends on</h3>
<ul>
<li><a href="../text-field">materials-text-field</a></li>
<li><a href="../menu">materials-menu</a></li>
<li><a href="../list-item">materials-list-item</a></li>
</ul>
<h3>Graph</h3>
<pre><code class="language-mermaid">graph TD;
  materials-autocomplete --&gt; materials-text-field
  materials-autocomplete --&gt; materials-menu
  materials-autocomplete --&gt; materials-list-item
  style materials-autocomplete fill:#f9f,stroke:#333,stroke-width:4px
</code></pre>
<hr/>
<p><em>Built with <a href="https://stenciljs.com/">StencilJS</a></em></p>


      </Host>
    );
  }
}