/* tslint:disable */
/* auto-generated react proxies */
import { createReactComponent } from './react-component-lib';

import { JSX } from '@materials/core';

import { defineCustomElements, applyPolyfills } from '@materials\core\lib\loader';

applyPolyfills().then(() => { defineCustomElements(window); });
export const MaterialsAlertController = createReactComponent<JSX.MaterialsAlertController, HTMLMaterialsAlertControllerElement>('materials-alert-controller');
export const MaterialsAutocomplete = createReactComponent<JSX.MaterialsAutocomplete, HTMLMaterialsAutocompleteElement>('materials-autocomplete');
export const MaterialsButton = createReactComponent<JSX.MaterialsButton, HTMLMaterialsButtonElement>('materials-button');
export const MaterialsCard = createReactComponent<JSX.MaterialsCard, HTMLMaterialsCardElement>('materials-card');
export const MaterialsCardAction = createReactComponent<JSX.MaterialsCardAction, HTMLMaterialsCardActionElement>('materials-card-action');
export const MaterialsCardContent = createReactComponent<JSX.MaterialsCardContent, HTMLMaterialsCardContentElement>('materials-card-content');
export const MaterialsCheckbox = createReactComponent<JSX.MaterialsCheckbox, HTMLMaterialsCheckboxElement>('materials-checkbox');
export const MaterialsChip = createReactComponent<JSX.MaterialsChip, HTMLMaterialsChipElement>('materials-chip');
export const MaterialsDatatable = createReactComponent<JSX.MaterialsDatatable, HTMLMaterialsDatatableElement>('materials-datatable');
export const MaterialsDatatableAction = createReactComponent<JSX.MaterialsDatatableAction, HTMLMaterialsDatatableActionElement>('materials-datatable-action');
export const MaterialsDatatableBody = createReactComponent<JSX.MaterialsDatatableBody, HTMLMaterialsDatatableBodyElement>('materials-datatable-body');
export const MaterialsDatatableBodyCell = createReactComponent<JSX.MaterialsDatatableBodyCell, HTMLMaterialsDatatableBodyCellElement>('materials-datatable-body-cell');
export const MaterialsDatatableBodyRow = createReactComponent<JSX.MaterialsDatatableBodyRow, HTMLMaterialsDatatableBodyRowElement>('materials-datatable-body-row');
export const MaterialsDatatableFooter = createReactComponent<JSX.MaterialsDatatableFooter, HTMLMaterialsDatatableFooterElement>('materials-datatable-footer');
export const MaterialsDatatableHeader = createReactComponent<JSX.MaterialsDatatableHeader, HTMLMaterialsDatatableHeaderElement>('materials-datatable-header');
export const MaterialsDatatableHeaderColumn = createReactComponent<JSX.MaterialsDatatableHeaderColumn, HTMLMaterialsDatatableHeaderColumnElement>('materials-datatable-header-column');
export const MaterialsDatatablePagination = createReactComponent<JSX.MaterialsDatatablePagination, HTMLMaterialsDatatablePaginationElement>('materials-datatable-pagination');
export const MaterialsDateField = createReactComponent<JSX.MaterialsDateField, HTMLMaterialsDateFieldElement>('materials-date-field');
export const MaterialsDatepicker = createReactComponent<JSX.MaterialsDatepicker, HTMLMaterialsDatepickerElement>('materials-datepicker');
export const MaterialsDialog = createReactComponent<JSX.MaterialsDialog, HTMLMaterialsDialogElement>('materials-dialog');
export const MaterialsDialogController = createReactComponent<JSX.MaterialsDialogController, HTMLMaterialsDialogControllerElement>('materials-dialog-controller');
export const MaterialsDrawer = createReactComponent<JSX.MaterialsDrawer, HTMLMaterialsDrawerElement>('materials-drawer');
export const MaterialsDrawerListItem = createReactComponent<JSX.MaterialsDrawerListItem, HTMLMaterialsDrawerListItemElement>('materials-drawer-list-item');
export const MaterialsDrawerWithTopAppBar = createReactComponent<JSX.MaterialsDrawerWithTopAppBar, HTMLMaterialsDrawerWithTopAppBarElement>('materials-drawer-with-top-app-bar');
export const MaterialsDropdown = createReactComponent<JSX.MaterialsDropdown, HTMLMaterialsDropdownElement>('materials-dropdown');
export const MaterialsExpansionPanel = createReactComponent<JSX.MaterialsExpansionPanel, HTMLMaterialsExpansionPanelElement>('materials-expansion-panel');
export const MaterialsFab = createReactComponent<JSX.MaterialsFab, HTMLMaterialsFabElement>('materials-fab');
export const MaterialsFormField = createReactComponent<JSX.MaterialsFormField, HTMLMaterialsFormFieldElement>('materials-form-field');
export const MaterialsHeadline = createReactComponent<JSX.MaterialsHeadline, HTMLMaterialsHeadlineElement>('materials-headline');
export const MaterialsIcon = createReactComponent<JSX.MaterialsIcon, HTMLMaterialsIconElement>('materials-icon');
export const MaterialsIconButton = createReactComponent<JSX.MaterialsIconButton, HTMLMaterialsIconButtonElement>('materials-icon-button');
export const MaterialsLinearProgress = createReactComponent<JSX.MaterialsLinearProgress, HTMLMaterialsLinearProgressElement>('materials-linear-progress');
export const MaterialsList = createReactComponent<JSX.MaterialsList, HTMLMaterialsListElement>('materials-list');
export const MaterialsListItem = createReactComponent<JSX.MaterialsListItem, HTMLMaterialsListItemElement>('materials-list-item');
export const MaterialsListItemCheckbox = createReactComponent<JSX.MaterialsListItemCheckbox, HTMLMaterialsListItemCheckboxElement>('materials-list-item-checkbox');
export const MaterialsMenu = createReactComponent<JSX.MaterialsMenu, HTMLMaterialsMenuElement>('materials-menu');
export const MaterialsMultipleSelect = createReactComponent<JSX.MaterialsMultipleSelect, HTMLMaterialsMultipleSelectElement>('materials-multiple-select');
export const MaterialsRadio = createReactComponent<JSX.MaterialsRadio, HTMLMaterialsRadioElement>('materials-radio');
export const MaterialsRadioGroup = createReactComponent<JSX.MaterialsRadioGroup, HTMLMaterialsRadioGroupElement>('materials-radio-group');
export const MaterialsSelect = createReactComponent<JSX.MaterialsSelect, HTMLMaterialsSelectElement>('materials-select');
export const MaterialsSnackbar = createReactComponent<JSX.MaterialsSnackbar, HTMLMaterialsSnackbarElement>('materials-snackbar');
export const MaterialsSnackbarController = createReactComponent<JSX.MaterialsSnackbarController, HTMLMaterialsSnackbarControllerElement>('materials-snackbar-controller');
export const MaterialsStep = createReactComponent<JSX.MaterialsStep, HTMLMaterialsStepElement>('materials-step');
export const MaterialsStepper = createReactComponent<JSX.MaterialsStepper, HTMLMaterialsStepperElement>('materials-stepper');
export const MaterialsSubtitle = createReactComponent<JSX.MaterialsSubtitle, HTMLMaterialsSubtitleElement>('materials-subtitle');
export const MaterialsSwitch = createReactComponent<JSX.MaterialsSwitch, HTMLMaterialsSwitchElement>('materials-switch');
export const MaterialsTab = createReactComponent<JSX.MaterialsTab, HTMLMaterialsTabElement>('materials-tab');
export const MaterialsTabs = createReactComponent<JSX.MaterialsTabs, HTMLMaterialsTabsElement>('materials-tabs');
export const MaterialsTextArea = createReactComponent<JSX.MaterialsTextArea, HTMLMaterialsTextAreaElement>('materials-text-area');
export const MaterialsTextField = createReactComponent<JSX.MaterialsTextField, HTMLMaterialsTextFieldElement>('materials-text-field');
export const MaterialsTimeField = createReactComponent<JSX.MaterialsTimeField, HTMLMaterialsTimeFieldElement>('materials-time-field');
export const MaterialsTimepicker = createReactComponent<JSX.MaterialsTimepicker, HTMLMaterialsTimepickerElement>('materials-timepicker');
export const MaterialsTopAppBar = createReactComponent<JSX.MaterialsTopAppBar, HTMLMaterialsTopAppBarElement>('materials-top-app-bar');
export const MaterialsTopAppBarAction = createReactComponent<JSX.MaterialsTopAppBarAction, HTMLMaterialsTopAppBarActionElement>('materials-top-app-bar-action');
