
import { Component, h, Host } from '@stencil/core';


@Component({
  tag: 'app-select-api',
  shadow: false
})
export class SelectApi {

  /*
  * DO NOT EDIT THIS FILE !!!
  * It has been auto generated from :
  * https://github.com/GMV-centravet/materials/blob/master/src/components/select/readme.md
  */

  render() {
    return (
      <Host class={{'api-page':true}}>
      <h1>materials-select</h1>

<h2>Properties</h2>
<table>
<thead>
<tr>
<th>Property</th>
<th>Attribute</th>
<th>Description</th>
<th>Type</th>
<th>Default</th>
</tr>
</thead>
<tbody>
<tr>
<td><code>box</code></td>
<td><code>box</code></td>
<td></td>
<td><code>boolean</code></td>
<td><code>undefined</code></td>
</tr>
<tr>
<td><code>customValidation</code></td>
<td>–</td>
<td></td>
<td><code>() =&gt; Promise&lt;string&gt;</code></td>
<td><code>undefined</code></td>
</tr>
<tr>
<td><code>defaultEmpty</code></td>
<td><code>default-empty</code></td>
<td></td>
<td><code>boolean</code></td>
<td><code>undefined</code></td>
</tr>
<tr>
<td><code>dense</code></td>
<td><code>dense</code></td>
<td></td>
<td><code>boolean</code></td>
<td><code>undefined</code></td>
</tr>
<tr>
<td><code>disabled</code></td>
<td><code>disabled</code></td>
<td></td>
<td><code>boolean</code></td>
<td><code>undefined</code></td>
</tr>
<tr>
<td><code>helperText</code></td>
<td><code>helper-text</code></td>
<td></td>
<td><code>string</code></td>
<td><code>undefined</code></td>
</tr>
<tr>
<td><code>label</code></td>
<td><code>label</code></td>
<td></td>
<td><code>string</code></td>
<td><code>undefined</code></td>
</tr>
<tr>
<td><code>leadingIcon</code></td>
<td><code>leading-icon</code></td>
<td></td>
<td><code>string</code></td>
<td><code>undefined</code></td>
</tr>
<tr>
<td><code>name</code></td>
<td><code>name</code></td>
<td></td>
<td><code>string</code></td>
<td><code>undefined</code></td>
</tr>
<tr>
<td><code>options</code></td>
<td>–</td>
<td></td>
<td><code>Map&lt;string | number | string[], string&gt;</code></td>
<td><code>undefined</code></td>
</tr>
<tr>
<td><code>outlined</code></td>
<td><code>outlined</code></td>
<td></td>
<td><code>boolean</code></td>
<td><code>undefined</code></td>
</tr>
<tr>
<td><code>required</code></td>
<td><code>required</code></td>
<td></td>
<td><code>boolean</code></td>
<td><code>undefined</code></td>
</tr>
<tr>
<td><code>value</code></td>
<td><code>value</code></td>
<td></td>
<td><code>any</code></td>
<td><code>undefined</code></td>
</tr>
<tr>
<td><code>width</code></td>
<td><code>width</code></td>
<td></td>
<td><code>string</code></td>
<td><code>undefined</code></td>
</tr>
</tbody>
</table>
<h2>Events</h2>
<table>
<thead>
<tr>
<th>Event</th>
<th>Description</th>
<th>Type</th>
</tr>
</thead>
<tbody>
<tr>
<td><code>change</code></td>
<td></td>
<td><code>CustomEvent&lt;any&gt;</code></td>
</tr>
<tr>
<td><code>select</code></td>
<td></td>
<td><code>CustomEvent&lt;any&gt;</code></td>
</tr>
</tbody>
</table>
<h2>Methods</h2>
<h3><code>forceValidation() =&gt; Promise&lt;void&gt;</code></h3>
<h4>Returns</h4>
<p>Type: <code>Promise&lt;void&gt;</code></p>
<h3><code>isValid() =&gt; Promise&lt;boolean&gt;</code></h3>
<h4>Returns</h4>
<p>Type: <code>Promise&lt;boolean&gt;</code></p>
<hr/>
<p><em>Built with <a href="https://stenciljs.com/">StencilJS</a></em></p>


      </Host>
    );
  }
}