/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface AppButtonApi {}
  interface AppButtonDemo {}
  interface AppButtonTabs {}
  interface AppCardApi {}
  interface AppCardDemo {}
  interface AppCardTabs {}
  interface AppCheckboxDemo {}
  interface AppChipDemo {}
  interface AppDatatableDemo {}
  interface AppDatepickerDemo {}
  interface AppDemoCodeBlock {
    'blockTitle': string;
  }
  interface AppDemoTemplatePage {}
  interface AppDialogDemo {}
  interface AppDropdownDemo {}
  interface AppExpansionPanelDemo {}
  interface AppFabDemo {}
  interface AppHome {}
  interface AppIconDemo {}
  interface AppIntroductionPage {}
  interface AppProfile {
    'name': string;
  }
  interface AppRoot {}
}

declare global {


  interface HTMLAppButtonApiElement extends Components.AppButtonApi, HTMLStencilElement {}
  var HTMLAppButtonApiElement: {
    prototype: HTMLAppButtonApiElement;
    new (): HTMLAppButtonApiElement;
  };

  interface HTMLAppButtonDemoElement extends Components.AppButtonDemo, HTMLStencilElement {}
  var HTMLAppButtonDemoElement: {
    prototype: HTMLAppButtonDemoElement;
    new (): HTMLAppButtonDemoElement;
  };

  interface HTMLAppButtonTabsElement extends Components.AppButtonTabs, HTMLStencilElement {}
  var HTMLAppButtonTabsElement: {
    prototype: HTMLAppButtonTabsElement;
    new (): HTMLAppButtonTabsElement;
  };

  interface HTMLAppCardApiElement extends Components.AppCardApi, HTMLStencilElement {}
  var HTMLAppCardApiElement: {
    prototype: HTMLAppCardApiElement;
    new (): HTMLAppCardApiElement;
  };

  interface HTMLAppCardDemoElement extends Components.AppCardDemo, HTMLStencilElement {}
  var HTMLAppCardDemoElement: {
    prototype: HTMLAppCardDemoElement;
    new (): HTMLAppCardDemoElement;
  };

  interface HTMLAppCardTabsElement extends Components.AppCardTabs, HTMLStencilElement {}
  var HTMLAppCardTabsElement: {
    prototype: HTMLAppCardTabsElement;
    new (): HTMLAppCardTabsElement;
  };

  interface HTMLAppCheckboxDemoElement extends Components.AppCheckboxDemo, HTMLStencilElement {}
  var HTMLAppCheckboxDemoElement: {
    prototype: HTMLAppCheckboxDemoElement;
    new (): HTMLAppCheckboxDemoElement;
  };

  interface HTMLAppChipDemoElement extends Components.AppChipDemo, HTMLStencilElement {}
  var HTMLAppChipDemoElement: {
    prototype: HTMLAppChipDemoElement;
    new (): HTMLAppChipDemoElement;
  };

  interface HTMLAppDatatableDemoElement extends Components.AppDatatableDemo, HTMLStencilElement {}
  var HTMLAppDatatableDemoElement: {
    prototype: HTMLAppDatatableDemoElement;
    new (): HTMLAppDatatableDemoElement;
  };

  interface HTMLAppDatepickerDemoElement extends Components.AppDatepickerDemo, HTMLStencilElement {}
  var HTMLAppDatepickerDemoElement: {
    prototype: HTMLAppDatepickerDemoElement;
    new (): HTMLAppDatepickerDemoElement;
  };

  interface HTMLAppDemoCodeBlockElement extends Components.AppDemoCodeBlock, HTMLStencilElement {}
  var HTMLAppDemoCodeBlockElement: {
    prototype: HTMLAppDemoCodeBlockElement;
    new (): HTMLAppDemoCodeBlockElement;
  };

  interface HTMLAppDemoTemplatePageElement extends Components.AppDemoTemplatePage, HTMLStencilElement {}
  var HTMLAppDemoTemplatePageElement: {
    prototype: HTMLAppDemoTemplatePageElement;
    new (): HTMLAppDemoTemplatePageElement;
  };

  interface HTMLAppDialogDemoElement extends Components.AppDialogDemo, HTMLStencilElement {}
  var HTMLAppDialogDemoElement: {
    prototype: HTMLAppDialogDemoElement;
    new (): HTMLAppDialogDemoElement;
  };

  interface HTMLAppDropdownDemoElement extends Components.AppDropdownDemo, HTMLStencilElement {}
  var HTMLAppDropdownDemoElement: {
    prototype: HTMLAppDropdownDemoElement;
    new (): HTMLAppDropdownDemoElement;
  };

  interface HTMLAppExpansionPanelDemoElement extends Components.AppExpansionPanelDemo, HTMLStencilElement {}
  var HTMLAppExpansionPanelDemoElement: {
    prototype: HTMLAppExpansionPanelDemoElement;
    new (): HTMLAppExpansionPanelDemoElement;
  };

  interface HTMLAppFabDemoElement extends Components.AppFabDemo, HTMLStencilElement {}
  var HTMLAppFabDemoElement: {
    prototype: HTMLAppFabDemoElement;
    new (): HTMLAppFabDemoElement;
  };

  interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {}
  var HTMLAppHomeElement: {
    prototype: HTMLAppHomeElement;
    new (): HTMLAppHomeElement;
  };

  interface HTMLAppIconDemoElement extends Components.AppIconDemo, HTMLStencilElement {}
  var HTMLAppIconDemoElement: {
    prototype: HTMLAppIconDemoElement;
    new (): HTMLAppIconDemoElement;
  };

  interface HTMLAppIntroductionPageElement extends Components.AppIntroductionPage, HTMLStencilElement {}
  var HTMLAppIntroductionPageElement: {
    prototype: HTMLAppIntroductionPageElement;
    new (): HTMLAppIntroductionPageElement;
  };

  interface HTMLAppProfileElement extends Components.AppProfile, HTMLStencilElement {}
  var HTMLAppProfileElement: {
    prototype: HTMLAppProfileElement;
    new (): HTMLAppProfileElement;
  };

  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };
  interface HTMLElementTagNameMap {
    'app-button-api': HTMLAppButtonApiElement;
    'app-button-demo': HTMLAppButtonDemoElement;
    'app-button-tabs': HTMLAppButtonTabsElement;
    'app-card-api': HTMLAppCardApiElement;
    'app-card-demo': HTMLAppCardDemoElement;
    'app-card-tabs': HTMLAppCardTabsElement;
    'app-checkbox-demo': HTMLAppCheckboxDemoElement;
    'app-chip-demo': HTMLAppChipDemoElement;
    'app-datatable-demo': HTMLAppDatatableDemoElement;
    'app-datepicker-demo': HTMLAppDatepickerDemoElement;
    'app-demo-code-block': HTMLAppDemoCodeBlockElement;
    'app-demo-template-page': HTMLAppDemoTemplatePageElement;
    'app-dialog-demo': HTMLAppDialogDemoElement;
    'app-dropdown-demo': HTMLAppDropdownDemoElement;
    'app-expansion-panel-demo': HTMLAppExpansionPanelDemoElement;
    'app-fab-demo': HTMLAppFabDemoElement;
    'app-home': HTMLAppHomeElement;
    'app-icon-demo': HTMLAppIconDemoElement;
    'app-introduction-page': HTMLAppIntroductionPageElement;
    'app-profile': HTMLAppProfileElement;
    'app-root': HTMLAppRootElement;
  }
}

declare namespace LocalJSX {
  interface AppButtonApi extends JSXBase.HTMLAttributes<HTMLAppButtonApiElement> {}
  interface AppButtonDemo extends JSXBase.HTMLAttributes<HTMLAppButtonDemoElement> {}
  interface AppButtonTabs extends JSXBase.HTMLAttributes<HTMLAppButtonTabsElement> {}
  interface AppCardApi extends JSXBase.HTMLAttributes<HTMLAppCardApiElement> {}
  interface AppCardDemo extends JSXBase.HTMLAttributes<HTMLAppCardDemoElement> {}
  interface AppCardTabs extends JSXBase.HTMLAttributes<HTMLAppCardTabsElement> {}
  interface AppCheckboxDemo extends JSXBase.HTMLAttributes<HTMLAppCheckboxDemoElement> {}
  interface AppChipDemo extends JSXBase.HTMLAttributes<HTMLAppChipDemoElement> {}
  interface AppDatatableDemo extends JSXBase.HTMLAttributes<HTMLAppDatatableDemoElement> {}
  interface AppDatepickerDemo extends JSXBase.HTMLAttributes<HTMLAppDatepickerDemoElement> {}
  interface AppDemoCodeBlock extends JSXBase.HTMLAttributes<HTMLAppDemoCodeBlockElement> {
    'blockTitle'?: string;
  }
  interface AppDemoTemplatePage extends JSXBase.HTMLAttributes<HTMLAppDemoTemplatePageElement> {}
  interface AppDialogDemo extends JSXBase.HTMLAttributes<HTMLAppDialogDemoElement> {}
  interface AppDropdownDemo extends JSXBase.HTMLAttributes<HTMLAppDropdownDemoElement> {}
  interface AppExpansionPanelDemo extends JSXBase.HTMLAttributes<HTMLAppExpansionPanelDemoElement> {}
  interface AppFabDemo extends JSXBase.HTMLAttributes<HTMLAppFabDemoElement> {}
  interface AppHome extends JSXBase.HTMLAttributes<HTMLAppHomeElement> {}
  interface AppIconDemo extends JSXBase.HTMLAttributes<HTMLAppIconDemoElement> {}
  interface AppIntroductionPage extends JSXBase.HTMLAttributes<HTMLAppIntroductionPageElement> {}
  interface AppProfile extends JSXBase.HTMLAttributes<HTMLAppProfileElement> {
    'name'?: string;
  }
  interface AppRoot extends JSXBase.HTMLAttributes<HTMLAppRootElement> {}

  interface IntrinsicElements {
    'app-button-api': AppButtonApi;
    'app-button-demo': AppButtonDemo;
    'app-button-tabs': AppButtonTabs;
    'app-card-api': AppCardApi;
    'app-card-demo': AppCardDemo;
    'app-card-tabs': AppCardTabs;
    'app-checkbox-demo': AppCheckboxDemo;
    'app-chip-demo': AppChipDemo;
    'app-datatable-demo': AppDatatableDemo;
    'app-datepicker-demo': AppDatepickerDemo;
    'app-demo-code-block': AppDemoCodeBlock;
    'app-demo-template-page': AppDemoTemplatePage;
    'app-dialog-demo': AppDialogDemo;
    'app-dropdown-demo': AppDropdownDemo;
    'app-expansion-panel-demo': AppExpansionPanelDemo;
    'app-fab-demo': AppFabDemo;
    'app-home': AppHome;
    'app-icon-demo': AppIconDemo;
    'app-introduction-page': AppIntroductionPage;
    'app-profile': AppProfile;
    'app-root': AppRoot;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


